### ISSUE TITLE
gemini流式输出中文乱码

### ISSUE THREAD

**Issue by lgf5090** [ultrasev/llmproxy-vercel#1]
![image](https://github.com/user-attachments/assets/226329a5-f089-43d1-8752-22d6a3d7ee81)

➜  ~ curl --location 'https://llmproxy-vercel-beta.454470.xyz/gemini/chat/completions' \
  --header 'Content-Type: application/json' \
  --header "Authorization: Bearer $GEMINI_API_KEY" \
  --data '{
    "model": "gemini-1.5-flash",
    "stream": true,
    "messages": [{"content": "你好", "role": "user"}],
    "temperature": 0,
    "max_tokens": 4096,
    "seed": 0,
    "top_p": 1
}'
data: {"id": "chatcmpl-1729536144", "object": "chat.completion.chunk", "created": 1729536144, "model": "gemini-1.5-flash", "choices": [{"index": 0, "delta": {"content": "\u00e4\u00bd\u00a0\u00e5\u00a5\u00bd\u00ef\u00bc\u0081 "}, "finish_reason": null}]}

data: {"id": "chatcmpl-1729536146", "object": "chat.completion.chunk", "created": 1729536146, "model": "gemini-1.5-flash", "choices": [{"index": 0, "delta": {"content": "\u00e5\u00be\u0088\u00e9\u00ab\u0098\u00e5\u0085\u00b4\u00e4\u00bd\u00a0\u00e8\u00b7\u009f\u00e6\u0088\u0091\u00e6\u0089\u0093\u00e6\u008b\u009b\u00e5\u0091\u00bc\u00e3\u0080\u0082\u00e4\u00bd\u00a0\u00e6\u0083\u00b3\u00e8\u0081\u008a\u00e4\u00ba\u009b\u00e4\u00bb\u0080\u00e4\u00b9\u0088\u00e5\u0091\u00a2\u00ef\u00bc\u009f \n"}, "finish_reason": null}]}

data: {"id": "chatcmpl-1729536146", "object": "chat.completion.chunk", "created": 1729536146, "model": "gemini-1.5-flash", "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}]}

data: [DONE]

➜  ~ curl --location 'https://llmproxy-vercel-beta.454470.xyz/gemini/chat/completions' \
  --header 'Content-Type: application/json' \
  --header "Authorization: Bearer $GEMINI_API_KEY" \
  --data '{
    "model": "gemini-1.5-flash",
    "stream": true,
    "messages": [{"content": "hello", "role": "user"}],
    "temperature": 0,
    "max_tokens": 4096,
    "seed": 0,
    "top_p": 1
}'
data: {"id": "chatcmpl-1729536168", "object": "chat.completion.chunk", "created": 1729536168, "model": "gemini-1.5-flash", "choices": [{"index": 0, "delta": {"content": "Hello! "}, "finish_reason": null}]}

data: {"id": "chatcmpl-1729536168", "object": "chat.completion.chunk", "created": 1729536168, "model": "gemini-1.5-flash", "choices": [{"index": 0, "delta": {"content": "How can I help you today? \n"}, "finish_reason": null}]}

data: {"id": "chatcmpl-1729536168", "object": "chat.completion.chunk", "created": 1729536168, "model": "gemini-1.5-flash", "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}]}

data: [DONE]

**Comment by ultrasev** [comment]
感谢发现问题，转义问题已修复，再试一下。 

![image](https://github.com/user-attachments/assets/d9a99de0-374f-4309-bc68-39da0ee9b262)

**Comment by lgf5090** [comment]
现在ok了
